[pytest]
testpaths =
    api_tests/tests
    ui_tests/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --alluredir=reports/allure-results --clean-alluredir
markers =
    api: API automation tests
    smoke: Core smoke tests
    ui: UI automation tests
    perf: Performance tests
